name: Job Scraper Bot

on:
  schedule:
    - cron: "0 */3 * * *"  # Runs every 3 hours (job scraper)
    - cron: "0 */6 * * *"  # Runs every 6 hours (email sender)
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set Up Environment Variables
        run: |
          echo "FIREBASE_CREDENTIALS_JSON='${{ secrets.FIREBASE_CREDENTIALS_JSON }}'" >> $GITHUB_ENV
          echo "EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }}" >> $GITHUB_ENV
          echo "LOCATION=${{ secrets.LOCATION }}" >> $GITHUB_ENV

      - name: Run Job Scraper
        run: python main.py

  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set Up Environment Variables
        run: |
          echo "FIREBASE_CREDENTIALS_JSON='${{ secrets.FIREBASE_CREDENTIALS_JSON }}'" >> $GITHUB_ENV
          echo "EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }}" >> $GITHUB_ENV
          echo "LOCATION=${{ secrets.LOCATION }}" >> $GITHUB_ENV

      - name: Send Job Alert Emails
        run: python email_service/send_email.py